{
  "formatVersion": "1.1",
  "component": {
    "group": "xyz.dynamic",
    "module": "dynamic-sdk-external-wallet",
    "version": "2.0.0-beta.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "xyz.dynamic",
          "module": "dynamic-sdk",
          "version": {
            "requires": "2.0.0-beta.1"
          }
        },
        {
          "group": "com.reown",
          "module": "sign",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.reown",
          "module": "android-core",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "dynamic-sdk-external-wallet-2.0.0-beta.1.aar",
          "url": "dynamic-sdk-external-wallet-2.0.0-beta.1.aar",
          "size": 213372,
          "sha512": "7025273cc0e7379f43956a6529e4965f75252054c4da16b12b2fd0ab48986244d3377147325c4eb60a57cd3a1f7b684a6f5bfcfd60078543d415265e466e8426",
          "sha256": "c52fb36ea42b8377f4abb6e7037cf8b3066d85846eb0cc0d167eb5207d1c87ad",
          "sha1": "b67927319713000833bc419daee973e67a891458",
          "md5": "ca512004f5ee2b48d35de876bed95c50"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.web3j",
          "module": "crypto",
          "version": {
            "requires": "4.9.8-hotfix"
          }
        },
        {
          "group": "xyz.dynamic",
          "module": "dynamic-sdk",
          "version": {
            "requires": "2.0.0-beta.1"
          }
        },
        {
          "group": "com.reown",
          "module": "sign",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.reown",
          "module": "android-core",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "dynamic-sdk-external-wallet-2.0.0-beta.1.aar",
          "url": "dynamic-sdk-external-wallet-2.0.0-beta.1.aar",
          "size": 213372,
          "sha512": "7025273cc0e7379f43956a6529e4965f75252054c4da16b12b2fd0ab48986244d3377147325c4eb60a57cd3a1f7b684a6f5bfcfd60078543d415265e466e8426",
          "sha256": "c52fb36ea42b8377f4abb6e7037cf8b3066d85846eb0cc0d167eb5207d1c87ad",
          "sha1": "b67927319713000833bc419daee973e67a891458",
          "md5": "ca512004f5ee2b48d35de876bed95c50"
        }
      ]
    }
  ]
}
