{
  "formatVersion": "1.1",
  "component": {
    "group": "xyz.dynamic",
    "module": "dynamic-sdk-export-private-key",
    "version": "2.0.0-beta.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "xyz.dynamic",
          "module": "dynamic-sdk",
          "version": {
            "requires": "2.0.0-beta.1"
          }
        },
        {
          "group": "xyz.dynamic",
          "module": "dynamic-sdk-internal-waas-engine",
          "version": {
            "requires": "2.0.0-beta.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "dynamic-sdk-export-private-key-2.0.0-beta.1.aar",
          "url": "dynamic-sdk-export-private-key-2.0.0-beta.1.aar",
          "size": 30680,
          "sha512": "964dcdb0afcd7460bd63cc3fc331dad70c7d2af77ed9a2bb87e56de741e325c956f3623697b75da5bbdbafaf854a0d48f01caa26b3b1ad7199b066679fa4859c",
          "sha256": "a565e8ca621abde14647480edf9573f7a9acca1dd073befcfa5be82f1d4d5dc6",
          "sha1": "14a01b94a6b9fea77c712b5e1d3dc004a2570d45",
          "md5": "286768b5faa462ada2f88b70ca271d60"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "xyz.dynamic",
          "module": "dynamic-sdk",
          "version": {
            "requires": "2.0.0-beta.1"
          }
        },
        {
          "group": "xyz.dynamic",
          "module": "dynamic-sdk-internal-waas-engine",
          "version": {
            "requires": "2.0.0-beta.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "dynamic-sdk-export-private-key-2.0.0-beta.1.aar",
          "url": "dynamic-sdk-export-private-key-2.0.0-beta.1.aar",
          "size": 30680,
          "sha512": "964dcdb0afcd7460bd63cc3fc331dad70c7d2af77ed9a2bb87e56de741e325c956f3623697b75da5bbdbafaf854a0d48f01caa26b3b1ad7199b066679fa4859c",
          "sha256": "a565e8ca621abde14647480edf9573f7a9acca1dd073befcfa5be82f1d4d5dc6",
          "sha1": "14a01b94a6b9fea77c712b5e1d3dc004a2570d45",
          "md5": "286768b5faa462ada2f88b70ca271d60"
        }
      ]
    }
  ]
}
