{
  "formatVersion": "1.1",
  "component": {
    "group": "xyz.dynamic",
    "module": "dynamic-sdk-business-account",
    "version": "2.0.0-beta.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "xyz.dynamic",
          "module": "dynamic-sdk",
          "version": {
            "requires": "2.0.0-beta.1"
          }
        },
        {
          "group": "xyz.dynamic",
          "module": "dynamic-sdk-waas",
          "version": {
            "requires": "2.0.0-beta.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "dynamic-sdk-business-account-2.0.0-beta.1.aar",
          "url": "dynamic-sdk-business-account-2.0.0-beta.1.aar",
          "size": 291003,
          "sha512": "c053a27b421b3680dfaab9f5b46e8c6b8e1aee2c54282a8159bf1e2d27ace2e0c631fa819873ce8bb212b7cb98789938e021e632208993e8eb60c8f8c4bbd31a",
          "sha256": "2a6e058821d62d237a87251ee6978993b853d4a4e68483d8185454cdbcf6e703",
          "sha1": "334a7bd6cef38fc4572f95000d042feff08ae1c2",
          "md5": "b42f2a81405626c3a9e9a1cb2bef3607"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "xyz.dynamic",
          "module": "dynamic-sdk",
          "version": {
            "requires": "2.0.0-beta.1"
          }
        },
        {
          "group": "xyz.dynamic",
          "module": "dynamic-sdk-waas",
          "version": {
            "requires": "2.0.0-beta.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "dynamic-sdk-business-account-2.0.0-beta.1.aar",
          "url": "dynamic-sdk-business-account-2.0.0-beta.1.aar",
          "size": 291003,
          "sha512": "c053a27b421b3680dfaab9f5b46e8c6b8e1aee2c54282a8159bf1e2d27ace2e0c631fa819873ce8bb212b7cb98789938e021e632208993e8eb60c8f8c4bbd31a",
          "sha256": "2a6e058821d62d237a87251ee6978993b853d4a4e68483d8185454cdbcf6e703",
          "sha1": "334a7bd6cef38fc4572f95000d042feff08ae1c2",
          "md5": "b42f2a81405626c3a9e9a1cb2bef3607"
        }
      ]
    }
  ]
}
