{
  "formatVersion": "1.1",
  "component": {
    "group": "xyz.dynamic",
    "module": "dynamic-sdk-external-wallet-coinbase",
    "version": "2.0.0-beta.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "xyz.dynamic",
          "module": "dynamic-sdk-external-wallet",
          "version": {
            "requires": "2.0.0-beta.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "dynamic-sdk-external-wallet-coinbase-2.0.0-beta.1.aar",
          "url": "dynamic-sdk-external-wallet-coinbase-2.0.0-beta.1.aar",
          "size": 33508,
          "sha512": "2afae088a1c5d3ab6fe1b8f7ffdfb93ad99d36d03a568b8b7f4e8e5814fae8fe1f87396d8f220afed977754bbb640c7498ecfdf4c2f9668fde65128f783a1a33",
          "sha256": "0ae5fefbfb51bca78c7c675fc3a359dae266f9848cbed857d75fc81ce9a164ff",
          "sha1": "6705f4fa24bc4a8b4844044229e2af1d106270a2",
          "md5": "7ae35211a8075135e63ce9cfc903c908"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.web3j",
          "module": "crypto",
          "version": {
            "requires": "4.9.8-hotfix"
          }
        },
        {
          "group": "xyz.dynamic",
          "module": "dynamic-sdk-external-wallet",
          "version": {
            "requires": "2.0.0-beta.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "dynamic-sdk-external-wallet-coinbase-2.0.0-beta.1.aar",
          "url": "dynamic-sdk-external-wallet-coinbase-2.0.0-beta.1.aar",
          "size": 33508,
          "sha512": "2afae088a1c5d3ab6fe1b8f7ffdfb93ad99d36d03a568b8b7f4e8e5814fae8fe1f87396d8f220afed977754bbb640c7498ecfdf4c2f9668fde65128f783a1a33",
          "sha256": "0ae5fefbfb51bca78c7c675fc3a359dae266f9848cbed857d75fc81ce9a164ff",
          "sha1": "6705f4fa24bc4a8b4844044229e2af1d106270a2",
          "md5": "7ae35211a8075135e63ce9cfc903c908"
        }
      ]
    }
  ]
}
