{
  "formatVersion": "1.1",
  "component": {
    "group": "xyz.dynamic",
    "module": "dynamic-sdk-solana",
    "version": "2.0.0-beta.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "xyz.dynamic",
          "module": "dynamic-sdk",
          "version": {
            "requires": "2.0.0-beta.1"
          }
        },
        {
          "group": "com.solanamobile",
          "module": "web3-solana",
          "version": {
            "requires": "0.3.0-beta4"
          }
        },
        {
          "group": "com.solanamobile",
          "module": "rpc-solana",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "com.solanamobile",
          "module": "rpc-core",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "com.solanamobile",
          "module": "rpc-okiodriver",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "dynamic-sdk-solana-2.0.0-beta.1.aar",
          "url": "dynamic-sdk-solana-2.0.0-beta.1.aar",
          "size": 41441,
          "sha512": "346f5e9e586761e171bd744f4c453702280835b29490693391f96a7ffbe6c1052c9a87b8709b8e3a20ccb233189ac197b8bc79e0999a93e27842a7b190178902",
          "sha256": "f9b292d494f1b4778a804c4aa46ce52cb9d0c44efa6b449def697b3cba06872d",
          "sha1": "ad7439308be9e3ddb7da1b846c3cca7583b6118c",
          "md5": "1a958201eb89ec2f4dd8aafca0db862f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "xyz.dynamic",
          "module": "dynamic-sdk",
          "version": {
            "requires": "2.0.0-beta.1"
          }
        },
        {
          "group": "com.solanamobile",
          "module": "web3-solana",
          "version": {
            "requires": "0.3.0-beta4"
          }
        },
        {
          "group": "com.solanamobile",
          "module": "rpc-solana",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "com.solanamobile",
          "module": "rpc-core",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "com.solanamobile",
          "module": "rpc-okiodriver",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "dynamic-sdk-solana-2.0.0-beta.1.aar",
          "url": "dynamic-sdk-solana-2.0.0-beta.1.aar",
          "size": 41441,
          "sha512": "346f5e9e586761e171bd744f4c453702280835b29490693391f96a7ffbe6c1052c9a87b8709b8e3a20ccb233189ac197b8bc79e0999a93e27842a7b190178902",
          "sha256": "f9b292d494f1b4778a804c4aa46ce52cb9d0c44efa6b449def697b3cba06872d",
          "sha1": "ad7439308be9e3ddb7da1b846c3cca7583b6118c",
          "md5": "1a958201eb89ec2f4dd8aafca0db862f"
        }
      ]
    }
  ]
}
