{
  "formatVersion": "1.1",
  "component": {
    "group": "xyz.dynamic",
    "module": "dynamic-sdk",
    "version": "2.0.0-beta.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.google.crypto.tink",
          "module": "tink-android",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.credentials",
          "module": "credentials",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.credentials",
          "module": "credentials-play-services-auth",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "dynamic-sdk-2.0.0-beta.1.aar",
          "url": "dynamic-sdk-2.0.0-beta.1.aar",
          "size": 1236373,
          "sha512": "c9f2fcfcc3faa4b49d2d5977479ff54529f573673337b521c8e82bd748af51c84a68fdf63269058eaa65756cdec641752a117ce46a3497ceda5f581bd2da62fc",
          "sha256": "8aa27313e63b16f237fc61d563fe7284a5d80d47e270c88c822edf5f0a7d1043",
          "sha1": "1febbdd4524b438ac3fc06a0de67abfdb6b192c4",
          "md5": "9017dc831b557ead5e2cb8ed244289a0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.google.crypto.tink",
          "module": "tink-android",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.credentials",
          "module": "credentials",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.credentials",
          "module": "credentials-play-services-auth",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "dynamic-sdk-2.0.0-beta.1.aar",
          "url": "dynamic-sdk-2.0.0-beta.1.aar",
          "size": 1236373,
          "sha512": "c9f2fcfcc3faa4b49d2d5977479ff54529f573673337b521c8e82bd748af51c84a68fdf63269058eaa65756cdec641752a117ce46a3497ceda5f581bd2da62fc",
          "sha256": "8aa27313e63b16f237fc61d563fe7284a5d80d47e270c88c822edf5f0a7d1043",
          "sha1": "1febbdd4524b438ac3fc06a0de67abfdb6b192c4",
          "md5": "9017dc831b557ead5e2cb8ed244289a0"
        }
      ]
    }
  ]
}
