{
  "formatVersion": "1.1",
  "component": {
    "group": "xyz.dynamic",
    "module": "dynamic-sdk-ton",
    "version": "2.0.0-beta.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "xyz.dynamic",
          "module": "dynamic-sdk",
          "version": {
            "requires": "2.0.0-beta.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "dynamic-sdk-ton-2.0.0-beta.1.aar",
          "url": "dynamic-sdk-ton-2.0.0-beta.1.aar",
          "size": 63886,
          "sha512": "23cab463ef924ba2fa19cff5d021e44b6786b76e97ef004d10b3539b6c069f618e228956231009b20370fdb45c971d290d38462ce306967c1fc3b16d5b44ce96",
          "sha256": "dd732dad480c320874b99911bf968d4a7410e2e4f3ee11096cb1f4c12eb94b81",
          "sha1": "4070bc56e96d5336554f47fae0ac5976f70a1dc4",
          "md5": "22c363ec5b8f07e0db7824c2258d1f04"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ton",
          "module": "ton-kotlin-block-tlb",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.ton",
          "module": "ton-kotlin-tvm",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "xyz.dynamic",
          "module": "dynamic-sdk",
          "version": {
            "requires": "2.0.0-beta.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "dynamic-sdk-ton-2.0.0-beta.1.aar",
          "url": "dynamic-sdk-ton-2.0.0-beta.1.aar",
          "size": 63886,
          "sha512": "23cab463ef924ba2fa19cff5d021e44b6786b76e97ef004d10b3539b6c069f618e228956231009b20370fdb45c971d290d38462ce306967c1fc3b16d5b44ce96",
          "sha256": "dd732dad480c320874b99911bf968d4a7410e2e4f3ee11096cb1f4c12eb94b81",
          "sha1": "4070bc56e96d5336554f47fae0ac5976f70a1dc4",
          "md5": "22c363ec5b8f07e0db7824c2258d1f04"
        }
      ]
    }
  ]
}
